version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      TZ: ${Time_ZONE}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/docker-volumes-data/mysql:/var/lib/mysql
    ports:
      - "13307:3306"
    networks:
      - rms
  redis:
    container_name: redis
    image: redis:4-alpine
    volumes:
      - ./docker/docker-volumes-data/redis:/data
    ports:
      - "16379:6379"
    networks:
      - rms

networks:
  rms:
    driver: bridge
